dist: jammy

language: shell

# compiler: gcc

branches:
  only:
    - master

services:
  - docker

before_install:
  - |
    echo "Installing libdap from RPMs"
    set -eux
    pip3 install awscli
    LIBDAP_RPM="libdap-3.21.1-99.el8.x86_64.rpm"
    aws s3 cp "s3://opendap.travis.build/${LIBDAP_RPM}" $TRAVIS_BUILD_DIR
    sudo dnf -y install "$LIBDAP_RPM"
    set +eux
  - |
    echo "Pulling most recent hyrax snapshot image"
    docker run -d -h hyrax -p 8080:8080 --name=hyrax_container opendap/hyrax:snapshot -n http://localhost:8080
    docker ps -a

before_script:
  - autoreconf --force --install --verbose
  
stages:
  - name: test

jobs:
  include:
  - stage: test
    script: 
    - ./configure
    - make check
    - echo "DONE"
    
